
variables:
    GIT_SUBMODULE_STRATEGY: recursive
stages:
  - build

before_script:
  # Force color CMake output even when output is not TTY
  - export CLICOLOR_FORCE=true
  - export ORDENV_SITE_PROFILE=20190814
  - export ORDENV_COMM_PROFILE=eccc/20191002
  - export ORDENV_GROUP_PROFILE=eccc/cmc/1.8
  - set +e ; . /fs/ssm/main/env/ordenv-boot-20200204.sh ; set -e
  - cd src
  - setup_ubuntu-18.04-amd64-64_intel-19.0.3.199.dot
build_cmake:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_INSTALL_PREFIX=${CI_PROJECT_DIR}/install-dir
    - make
    - make check
    - ./test_f_pgsm
    - make install
  artifacts:
    paths:
      - install-dir
