
variables:
    GIT_SUBMODULE_STRATEGY: recursive
stages:
  - build

before_script:
  # Force color CMake output even when output is not TTY
  - export CLICOLOR_FORCE=true
build_cmake:
  stage: build
  script:
    - source ~/ci-admin-bundle/environments/eccc-setup-intel.sh
    - mkdir build
    - cd build
    - cmake ../src -DCMAKE_INSTALL_PREFIX=${CI_PROJECT_DIR}/install-dir
    - make
  artifacts:
    paths:
      - install-dir
