
variables:
    GIT_SUBMODULE_STRATEGY: recursive
stages:
  - build
#  - test
#  - package
#  - deploy

before_script:
  # Force color CMake output even when output is not TTY
  - export CLICOLOR_FORCE=true

build_intel-19.0.3:
  stage: build
  script:
    - source ~/ci-admin-bundle/environments/latest/ubuntu-18.04-skylake-64/intel-19.0.3.199.sh
    - mkdir build
    - cd build
    - cmake ../ -DCMAKE_INSTALL_PREFIX=${CI_PROJECT_DIR}/install-dir
    - make
  artifacts:
    paths:
      - install-dir

build_gnu-7.4.0:
  stage: build
  script:
    - source ~/ci-admin-bundle/environments/latest/ubuntu-18.04-amd-64/gnu-7.4.0.sh
    - mkdir build
    - cd build
    - cmake ../ -DCMAKE_INSTALL_PREFIX=${CI_PROJECT_DIR}/install-dir
    - make
  artifacts:
    paths:
      - install-dir
