variables:
   GIT_SUBMODULE_STRATEGY: recursive
stages:
   - build
   - test
#   - package
#   - deploy

before_script:
   # Force color CMake output even when output is not TTY
   - export CLICOLOR_FORCE=true

build:intel-19.0.3:
<<<<<<< HEAD
   stage: build
   only:
      - master
      - dev
   script:
      - source ci-env/latest/ubuntu-18.04-skylake-64/intel-19.0.3.199.sh
      - mkdir build_intel-19.0.3
      - cd build_intel-19.0.3
      - cmake ../ -DCMAKE_INSTALL_PREFIX=${CI_PROJECT_DIR}/install-dir
      - make
   artifacts:
      expire_in: 2 hrs
      paths:
         - build_intel-19.0.3

build:gnu-7.4.0:
   stage: build
   only:
      - master
      - dev
   script:
      - source ci-env/latest/ubuntu-18.04-amd-64/gnu-7.4.0.sh
      - mkdir build_gnu-7.4.0
      - cd build_gnu-7.4.0
      - cmake ../ -DCMAKE_INSTALL_PREFIX=${CI_PROJECT_DIR}/install-dir
      - make
   artifacts:
      expire_in: 2 hrs
      paths:
         - build_gnu-7.4.0
=======
  stage: build
  script:
    - source ci-env/latest/ubuntu-18.04-skylake-64/intel-19.0.3.199.sh
    - mkdir build_intel
    - cd build_intel
    - cmake ../ -DCMAKE_INSTALL_PREFIX=${CI_PROJECT_DIR}/install-dir
    - make
  artifacts:
    expire_in: 2 hrs
    paths:
      - build_intel

build:gnu-7.4.0:
  stage: build
  script:
    - source ci-env/latest/ubuntu-18.04-amd-64/gnu-7.4.0.sh
    - mkdir build_gnu
    - cd build_gnu
    - cmake ../ -DCMAKE_INSTALL_PREFIX=${CI_PROJECT_DIR}/install-dir
    - make
  artifacts:
    expire_in: 2 hrs
    paths:
      - build_gnu
>>>>>>> 9486d7b61a14c77f8164aff432217e2e50db3f75

test:intel-19.0.3:
   stage: test
   only:
      - master
      - dev
   script:
      - source ci-env/latest/ubuntu-18.04-amd-64/intel-19.0.3.199.sh
<<<<<<< HEAD
      - cd build_intel-19.0.3
=======
      - cd build_intel
>>>>>>> 9486d7b61a14c77f8164aff432217e2e50db3f75
      - make check

test:gnu-7.4.0:
   stage: test
   only:
      - master
      - dev
   script:
      - source ci-env/latest/ubuntu-18.04-amd-64/gnu-7.4.0.sh
<<<<<<< HEAD
      - cd build_gnu-7.4.0
=======
      - cd build_gnu
>>>>>>> 9486d7b61a14c77f8164aff432217e2e50db3f75
      - make check

