make tests ONLY=constructor_gen_1001
make tests ONLY=constructor_gen_1002_5001
make tests ONLY=constructor_gen_5002_5003_5005
make tests ONLY=constructor_build_2001
make tests ONLY=constructor_build_2001_stat
make tests ONLY=constructor_build_all
make tests ONLY=constructor_build_vert
make tests ONLY=constructor_gen_wrong_version
make tests ONLY=constructor
make tests ONLY=read_write_toc
# Next todo:
#make tests ONLY=read_write_read_all_write_read_all
#make tests ONLY=constructor_any
#constructor_simple_gen_1001 necessite vgd_print
