# User options
FFLAGS="$(FFLAGS_INTEL) -C -g"
DESCRIP_F_PATH = ../libf
DESCRIP_C_PATH = ../libc
# Use the setup* dot files in ../ to set the following variables 

# Override incorrect implicits
%.o : %.mod

# Define suffix rules
.SUFFIXES: .ftn90 .o
.ftn90.o:
	echo $(DESCRIP_F_PATH)
	s.compile -libpath $(MY_LIBPATH) $(LIBRARY_PATH) -optf =$(FFLAGS) -includes $(DESCRIP_F_PATH) -src $<

#OBJECTS = $(DESCRIP_F_PATH)/vgrid_descriptors.o $(DESCRIP_F_PATH)/vgrid_genab_5002.o $(DESCRIP_F_PATH)/vgrid_genab_1002_5001.o $(DESCRIP_F_PATH)/vgrid_genab_1001.o $(DESCRIP_F_PATH)/vgrid_genab_1004.o $(DESCRIP_F_PATH)/vgrid_genab_2001.o $(DESCRIP_F_PATH)/utils.o $(DESCRIP_F_PATH)/msg.o unit_testing.o

OBJECTS = $(DESCRIP_C_PATH)/vgrid.o $(DESCRIP_F_PATH)/vgrid_descriptors.o $(DESCRIP_F_PATH)/msg.o unit_testing.o

UNIT_TEST: UNIT_TEST.ftn90 $(OBJECTS)
	s.compile $(OPENMP) -optf =$(FFLAGS) -includes $(MY_INCLUDE_PATH) $(DESCRIP_F_PATH) $(INCLUDE_PATH) -obj $(OBJECTS) -src UNIT_TEST.ftn90 -o UNIT_TEST  -libpath $(MY_LIBPATH) $(LIBRARY_PATH) -libappl $(MODELUTILS) rmn

unit_testing.o: unit_testing.ftn90

$(DESCRIP_F_PATH)/vgrid_descriptors.o: $(DESCRIP_F_PATH)/vgrid_descriptors.ftn90
	(cd $(DESCRIP_F_PATH) && $(MAKE) vgrid_descriptors.o)

$(DESCRIP_F_PATH)/vgrid_genab_5002.o: $(DESCRIP_F_PATH)/vgrid_genab_5002.ftn90
	(cd $(DESCRIP_F_PATH) && $(MAKE) vgrid_genab_5002.o)

$(DESCRIP_F_PATH)/vgrid_genab_1002_5001.o: $(DESCRIP_F_PATH)/vgrid_genab_1002_5001.ftn90
	(cd $(DESCRIP_F_PATH) && $(MAKE) vgrid_genab_1002_5001.o)

$(DESCRIP_F_PATH)/vgrid_genab_1001.o: $(DESCRIP_F_PATH)/vgrid_genab_1001.ftn90
	(cd $(DESCRIP_F_PATH) && $(MAKE) vgrid_genab_1001.o)

$(DESCRIP_F_PATH)/vgrid_genab_1004.o: $(DESCRIP_F_PATH)/vgrid_genab_1004.ftn90
	(cd $(DESCRIP_F_PATH) && $(MAKE) vgrid_genab_1004.o)

$(DESCRIP_F_PATH)/utils.o: $(DESCRIP_F_PATH)/utils.ftn90
	(cd $(DESCRIP_F_PATH) && $(MAKE) utils.o)

$(DESCRIP_F_PATH)/msg.o: $(DESCRIP_F_PATH)/msg.ftn90
	(cd $(DESCRIP_F_PATH) && $(MAKE) msg.o)

$(DESCRIP_C_PATH)/vgrid.o: $(DESCRIP_C_PATH)/vgrid.c	
	(cd $(DESCRIP_C_PATH) && $(MAKE) vgrid.o)

clean:
	rm -f *.f90 *.o *.mod
